Mark sensors as diagnostic
DurgNomis-drol/ha_toyota pull request #86
Opened 2021-11-21 11:18 UTC by rfvermut

Unclutters default lovelace view

![image](https://user-images.githubusercontent.com/13441442/142759715-a5d623b7-6a24-43a2-872e-5aa5f637f586.png)

2021-11-21 11:31 UTC, DurgNomis-drol commented
Please make sure that all checks succeed. Run `poetry run pre-commit run --all-files` before commiting or to fix the errors that exists now and the push a new commit with these fixes 😊

2021-11-21 11:48 UTC, rfvermut commented
Oh, it opened a can of worms:

```
  And because homeassistant (2021.11.5) depends on httpx (0.19.0)
   and mytoyota (0.7.4) depends on httpx (>=0.18.1,<0.19.0), mytoyota (0.7.4) is incompatible with homeassistant (>=2021.11.1,<2022.0.0).
  So, because toyota depends on both homeassistant (^2021.11.1) and mytoyota (0.7.4), version solving failed.
```

2021-11-21 11:49 UTC, rfvermut commented
So depends on https://github.com/DurgNomis-drol/mytoyota/pull/105

2021-11-21 15:31 UTC, DurgNomis-drol requested changes
The `entity_category` is really not meant for integrations like this, though I like the initiative (Both yours and HA). Some sensors are straight forward, others like `starter_battery_health` would normally be in the `diagnostic` category, but in this instance it does not make sense. The same goes for some of those I made comments on below. As this is the first time we see this in HA, it is probably not in it's final form yet. This usually takes a couple of versions, so we will probably need to revisit this again.

2021-11-21 15:31 UTC, DurgNomis-drol commented on custom_components/toyota/binary_sensor.py
> +    _attr_entity_category = ENTITY_CATEGORY_DIAGNOSTIC
This should not be listed as diagnostic. It is meant for people to easily see if something is not right with car.

2021-11-21 15:31 UTC, DurgNomis-drol commented on custom_components/toyota/binary_sensor.py
> +    _attr_entity_category = ENTITY_CATEGORY_DIAGNOSTIC
Part of the HVAC system and does not belong in the diagnostic category. This sensor is not in it's final for yet. as I am not sure what the different numbers means.

2021-11-21 15:31 UTC, DurgNomis-drol commented on custom_components/toyota/binary_sensor.py
> +    _attr_entity_category = ENTITY_CATEGORY_DIAGNOSTIC
See above comment on FrontDefogger

2021-11-21 15:31 UTC, DurgNomis-drol commented on custom_components/toyota/entity.py
> +    _attr_entity_category = ENTITY_CATEGORY_DIAGNOSTIC
Statistics does not belong in the diagnostic category.

2021-11-21 16:45 UTC, DurgNomis-drol commented
Please rebase onto master, underlying issue with `httpx` has been fixed.

2021-11-22 08:38 UTC, DurgNomis-drol requested changes
One last thing! 😃

2021-11-22 08:38 UTC, DurgNomis-drol commented on pyproject.toml
> +homeassistant = "^2021.11.1"
```suggestion
homeassistant = ">=2021.11"
```

2021-11-22 08:43 UTC, DurgNomis-drol approved these changes
Awesome! Thanks for contributing! ❤️

2021-11-22 08:43 UTC, merged